const actions = {
  ASYNC_GET_ALL_PRODUCTS: '@actions/ASYNC_GET_ALL_PRODUCTS',
  SET_PRODUCTS: '@actions/SET_PRODUCTS',
  SET_IS_LOADING: '@actions/SET_IS_LOADING',
  TOGGLE_PRODUCT_CART: '@actions/TOGGLE_PRODUCT_CART',
  TOGGLE_PRODUCT_DELETE_CART: '@actions/TOGGLE_PRODUCT_DELETE_CART',
  DELETE_PRODUCT_LIST: '@actions/DELETE_PRODUCT_LIST',
};

export default actions;
